pipeline {
    agent any

    tools {
        maven 'Maven' // Assumes you have Maven tool configured in Jenkins
        jdk 'JDK' // Assumes you have JDK tool configured in Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                git 'https://your-repo-url.git'
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Install') {
            steps {
                sh 'mvn install'
            }
        }

        stage('Archive') {
            steps {
                archiveArtifacts artifacts: '**/target/*.jar', allowEmptyArchive: true
            }
        }
    }
}
